on:
  push:
    tags:
      - "*" # Push events to every tag not containing /

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout sources
        uses: actions/checkout@v3

      # https://github.com/dtolnay/rust-toolchain
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to https://crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
